# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XSH2
version:      2.1.0
version_from: lib/XML/XSH2/Functions.pm
installdirs:  site
requires:
    IO::Scalar:                    0
    Parse::RecDescent:             1.94
    XML::Filter::DOMFilter::LibXML: 0.02
    XML::LibXML:                   1.60
    XML::LibXML::Common:           0.13
    XML::LibXML::Iterator:         0
    XML::LibXML::XPathContext:     0.07
    XML::LibXSLT:                  1.60
    XML::SAX::Writer:              0.44
    XML::XUpdate::LibXML:          0.6.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
