--- #YAML:1.0
name:               XML-XSH2
version:            2.1.7
abstract:           XML Editing Shell
author:
    - Petr Pajas (pajas@matfyz.cz)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Scalar:           0
    Parse::RecDescent:    1.94
    Term::ReadLine:       0
    Term::ReadLine::Perl:  0
    URI:                  0
    XML::Filter::DOMFilter::LibXML:  0.02
    XML::LibXML:          1.60
    XML::LibXML::Common:  0.13
    XML::LibXML::Iterator:  0
    XML::LibXML::XPathContext:  0.07
    XML::LibXSLT:         1.60
    XML::SAX::Writer:     0.44
    XML::XUpdate::LibXML:  0.6.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
