--- #YAML:1.0
name:                XML-XSH2
version:             2.1.6
abstract:            XML Editing Shell
license:             ~
author:              
    - Petr Pajas (pajas@matfyz.cz)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Scalar:                    0
    Parse::RecDescent:             1.94
    Term::ReadLine:                0
    Term::ReadLine::Perl:          0
    URI:                           0
    XML::Filter::DOMFilter::LibXML: 0.02
    XML::LibXML:                   1.60
    XML::LibXML::Common:           0.13
    XML::LibXML::Iterator:         0
    XML::LibXML::XPathContext:     0.07
    XML::LibXSLT:                  1.60
    XML::SAX::Writer:              0.44
    XML::XUpdate::LibXML:          0.6.0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
